### ISSUE TITLE
intra vs inter chromosomal counts in input

### ISSUE THREAD

**Issue by armenabnousi** [ay-lab/fithic#13]
Hi, this is not a technical issue but rather it's not documented in the manual. I know fithic is for mid-range intrachromosomal contacts. In the input files, specifically the fragments file, does the marginalized count need to be for the intra counts only or for all counts?

Thanks!

**Comment by ay-lab** [comment]
Hi,
The reason why we suggest FitHiC for mid-range intrachr interactions is
that those make the most sense biologically. FitHiC works on all ranges and
on interchr counts as well and we made this much easier and faster with
Arya's FitHiC2 implementation.
For your question on marginalized counts, it really won't matter as the
number in that field is not used for any calculations. We just use it for
thresholding. Effectively you can put "1" or anything bigger for loci you
want to consider and "0" for anything you want to filter out and that would
be fine.
Best,

**Comment by armenabnousi** [comment]
thank you!
