### ISSUE TITLE
HTML file has broken links to FitHiC outputs

### ISSUE THREAD

**Issue by ckmah** [ay-lab/fithic#16]
I noticed the links in the HTML generated are missing the resolution specified when running FitHiC.

e.g. the equal occupancy bin statistics file:
```
SAMPLE.fithic_pass1.txt
```
should be (for resolution=5kb):
```
SAMPLE.fithic_pass1.[res5000.]txt
```

**Comment by aryakaul** [comment]
Hey Clarence! Thanks for the heads up. I've pushed a fix on a new branch 'html-bugfix' 

It uses a _slightly_ hacky way of determining the resolution. I can't seem to break the fix, but I was wondering if you could try testing it and seeing if you could find an issue with it?

If not, I'll go ahead an merge

**Comment by ckmah** [comment]
Looks good!

**Comment by aryakaul** [comment]
Merged! Thanks Clarence + Lucas for the help!
