### ISSUE TITLE
Illegal fragment pair

### ISSUE THREAD

**Issue by RuiqinZheng** [ay-lab/fithic#20]
Hello When I use the fithic ,I got a error :Illegal fragment pair, and the following is my input file
$ head fithic.interactionCounts
chr1	25000	chr1	25000	624.0
chr1	25000	chr1	75000	760.0
chr1	25000	chr1	125000	315.0
chr1	25000	chr1	175000	146.0
chr1	25000	chr1	225000	113.0
chr1	25000	chr1	275000	98.0
chr1	25000	chr1	325000	80.0
chr1	25000	chr1	375000	56.0
chr1	25000	chr1	425000	48.0
chr1	25000	chr1	475000	38.0

$ head fithic.fragmentMappability
chr1	0	25000	19005.0	1
chr1	50000	75000	28207.0	1
chr1	100000	125000	26814.0	1
chr1	150000	175000	18005.0	1
chr1	200000	225000	24461.0	1
chr1	250000	275000	23232.0	1

can you help me to solve this problem?
Thanks!
Best.

**Comment by aryakaul** [comment]
Hello! I think the issue is that your files are not gzipped. Please check the README, all input files must be compressed with the gzip protocol.

Best,
Arya

**Comment by aryakaul** [comment]
Closed for no response.

**Comment by armenabnousi** [comment]
I was running into the same problem. For future reference: your interactions file should not contain the main diagonal, i.e. columns 1,2 cannot be the same as columns 3,4. 
Also note that the fragments file is not sparse. It should include all fragments, even those with marginal count 0 (is that right?)

**Comment by ay-lab** [comment]
Hi Armen,
Yes that's correct with the diagonal entries though we should be throwing
more informative errors/warnings. We will fix this.
And yes the fragment file has to have every single fragment/bin/window even
if they will get filtered later on and/or have zero counts.
I think this script is supposed to do that for you anyway:
https://github.com/ay-lab/fithic/blob/master/fithic/utils/createFitHiCFragments-fixedsize.py

Best,
