### ISSUE TITLE
Minor bug when testing installation

### ISSUE THREAD

**Issue by kalavattam** [ay-lab/fithic#21]
Dear Ay lab,

Thank you for making and maintaining this great software for the community.

I caught one small bug when I was testing my fithic installation and thought I would let you know. In the directory biasPerLocus, the file Dixon_IMR90_HindIII_hg19_w100000.gz is missing positional and normalization information for chrY loci. This results in an error (stdout):

> Error. Bias file does not contain chromosome chr10 or chrY.                 Please ensure you're using correct file.

A little weird b/c chr10 is there in the file. Anyway, I added dummy information for chrY (set all normalization values to 1; see attached file) and that solved the problem.

Thanks again,
Kris

[Dixon_IMR90_HindIII_hg19_w100000_chrYnow.tsv.gz](https://github.com/ay-lab/fithic/files/2898434/Dixon_IMR90_HindIII_hg19_w100000_chrYnow.tsv.gz)

**Comment by kalavattam** [comment]
Moved to the Google Group.

**Comment by aryakaul** [comment]
Thanks Kris!

You're correct, I added a new test in the latest git release and haven’t yet modified the tests on github to account for this. This will be updated in the next release; but good catch! Your solution is the correct one.

Best,
Arya
