### ISSUE TITLE
Can fithic run low resolution HiC data？

### ISSUE THREAD

**Issue by Antony-1996** [ay-lab/fithic#24]
Can fithic run low resolution HiC data?

**Comment by ay-lab** [comment]
Yes. It learns the background from given data so any resolution would be
fine. You may want to look at the results closely to find an appropriate
threshold to be stringent say if you have high sequencing depth but are
still using a low resolution. Should be fine other than that.

**Comment by Antony-1996** [comment]
in fact ，low resolution is a kind of filtering that only significant interactions can be detect。so finding an appropriate threshold might be a righ。
