### ISSUE TITLE
error while using fithic for the interchromosomal interactions

### ISSUE THREAD

**Issue by Nohaosma** [ay-lab/fithic#25]
Dear Dr. Ay,
I used fithic for the intrachromosomal contacts and it worked perfectly.
I am trying to use fithic 2.0.7 for the interchromosomal contacts and here is my command:

python fithic.py -f fragments_list.gz -i chr9_chrX_1mb_fithic.gz -o test/ -r 1000000 -t bias.gz -x All
python fithic.py -f fragments_list.gz -i chr9_chrX_1mb_fithic.gz -o test/ -r 1000000 -t bias.gz -x interOnly

but it gives me this error:

File "fithic.py", line 310, in main
    (binStats,noOfFrags, maxPossibleGenomicDist, possibleIntraInRangeCount, possibleInterAllCount, interChrProb, baselineIntraChrProb)= generate_FragPairs(binStats, fragsFile, resolution)
  File "fithic.py", line 560, in generate_FragPairs
    currBin = binStats[binTracker]
KeyError: 0

Can you help me solve this issue???

Best regards,
Noha

**Comment by aryakaul** [comment]
Hey Noha! Could you provide the output of the following commands?

`zcat fragments_list.gz | cut -f1 | sort | uniq -c`
`zcat chr9_chrX_1mb_fithic.gz | cut -f1 | sort | uniq -c`
`zcat chr9_chrX_1mb_fithic.gz | cut -f3 | sort | uniq -c`

Also, does the '-x All' command also throw this error or just the 'interOnly'?

**Comment by Nohaosma** [comment]
zcat fragments_list.gz | cut -f1 | sort | uniq -c


    250 chr1
    136 chr10
    136 chr11
    134 chr12
    116 chr13
    108 chr14
    103 chr15
     91 chr16
     82 chr17
     79 chr18
     60 chr19
    244 chr2
     64 chr20
     49 chr21
     52 chr22
    199 chr3
    192 chr4
    181 chr5
    172 chr6
    160 chr7
    147 chr8
    142 chr9
    156 chrX
     60 chrY

zcat chr9_chrX_1mb_fithic.gz | cut -f1 | sort | uniq -c

  17245 9

zcat chr9_chrX_1mb_fithic.gz | cut -f3 | sort | uniq -c

  17245 X


Also, does the '-x All' command also throw this error or just the 'interOnly'?

I tried both and both gave the same error



Thank you so much

________________________________

**Comment by aryakaul** [comment]
I believe the error is because you are using a frag file with extra chromosomes not located in the interactions file. Remake the frags file keeping only lines that contain chr9 and chrX and try using that with FitHiC. Let me know if this fixes it!

**Comment by Nohaosma** [comment]
Dear Luak,


I did that and it gave me the same error.

I did grep only chromosome X and chromosome9 from the fragments list and tried it with -x All and didn't work and I tried with -x interOnly and it did not work too.


I am sorry for bothering you and thank you so much for your kind help


Best regards,

Noha Osman

________________________________

**Comment by aryakaul** [comment]
No problem! Would you be able to send over the log file that's created up until this point? You can send it to akaul@lji.org or if its short enough just paste it here.
