### ISSUE TITLE
Standard Error is always 0

### ISSUE THREAD

**Issue by joreynajr** [ay-lab/fithic#28]
Between lines 887 and 897 in fithic/fithic/fithic.py there is some commenting out of some standard error calculation?

**Comment by aryakaul** [comment]
Hey Joaquin,

Std error calculation previously used would have been too slow given how FitHiC2 is set up. We made the decision to nix it, but kept the column for consistent formatting. Don't believe there's currently any  plans to include it

**Comment by joreynajr** [comment]
Thanks Arya, I ended up not needing it but I appreciate the quick response. Just for future reference, if I did uncomment those lines would FitHiC2 then calculate std error?

**Comment by aryakaul** [comment]
Hey Joaquin, No underlying datastructures have changed which the old stderror calculation relied on.

**Comment by joreynajr** [comment]
Thanks Arya, I'll go ahead and close this.
