### ISSUE TITLE
Can't Open File

### ISSUE THREAD

**Issue by aakashsur** [ay-lab/fithic#29]
When using `merge-filter.sh` I run into:

```
python3: can't open file 'CombineNearbyInteraction.py': [Errno 2] No such file or directory
```

This is because a variable has been capitalized: 

https://github.com/ay-lab/fithic/blob/0eababa70e0b1ef91f0c38c5ca24f32d555e2fd4/fithic/utils/merge-filter.sh#L19

So the variable `$UTILITYFOLDER` is empty, whereas the variable `$utilityfolder` contains the argument needed. Not sure if this is bash version issue or something.

**Comment by aryakaul** [comment]
Not a bash version issue, just a typo. Thanks for catching this. I'll fix it in the repo!
