### ISSUE TITLE
Scikit-learn broken command

### ISSUE THREAD

**Issue by aakashsur** [ay-lab/fithic#3]
It looks like there's something wrong with a call to the isotonic module in scikit-learn. When running the example out of the box I got the error: 

`TypeError: fit() got an unexpected keyword argument 'increasing'`

After looking at your code, it looks like you are calling the fit_transform function from the Isotonic Regression module in scikit-learn which passes it to the fit function. It's hard to tell (https://github.com/scikit-learn/scikit-learn/blob/a24c8b46/sklearn/isotonic.py#L325) but I wasn't sure if it accepts additional parameters. It could via some mixin but removing "increasing=False" from line 276 seems to do the trick. (https://github.com/ay-lab/fithic/blob/master/fithic/fithic.py#L276)

Not sure if this is an update to scikit-learn or something that caused a change or if I managed to run it wrong.

**Comment by ay-lab** [comment]
Yes, it's been recently fixed! Thanks for the heads up, let me know if our new update fixed everything on your end.
