### ISSUE TITLE
error while running fithic with data generated by hic-pro

### ISSUE THREAD

**Issue by LinXialab** [ay-lab/fithic#49]
I used  the script in HiC-Pro to transform the 40Kb ICE-normalized Hi-C contact result matrix to a raw interaction count file and a bias file calculated by ICE, but got these error informations, could you please help me to fix this?

fithic -f fithic.fragmentMappability.gz  -i fithic.interactionCounts.gz -t fithic.biases.gz  -o fithic_sample2 -l TU-2 -v -x intraOnly -r 40000

Reading the contact counts file to generate bins...
Interactions file read. Time took 47.469826459884644
Fragments file read. Time took 0.20023465156555176
Traceback (most recent call last):
  File "/home/wg_xialin/.local/bin/fithic", line 8, in <module>
    sys.exit(main())
  File "/home/wg_xialin/.local/lib/python3.8/site-packages/fithic/fithic.py", line 314, in main
    biasDic = read_biases(biasFile)
  File "/home/wg_xialin/.local/lib/python3.8/site-packages/fithic/fithic.py", line 671, in read_biases
    chrom=words[0]; midPoint=int(words[1]); bias=float(words[2])
IndexError: list index out of range

**Comment by ay-lab** [comment]
Seems like your bias file does have a missing field in either one line or maybe throughout. Can you please look at the head and tail of that file and post it here?

**Comment by LinXialab** [comment]
Thanks for your reply.
The head of my bias file is :
nan
4.180014091011641231e-01
4.902934829325978905e-01
2.933587207959292287e-01
8.806121240049499810e-02
nan
3.200707494662100028e-01
nan
nan
nan

The tail of my bias file is:
1.534252469916840278e-01
nan
nan
nan
nan
nan
nan
nan
nan
9.588770128049324271e-01

**Comment by ay-lab** [comment]
The expected format is:
chr1	500000	1.0
chr1	1500000	0.323167182522
chr1	2500000	0.429284878284
chr1	3500000	0.432662465824
chr1	4500000	0.74520616616

**Comment by LinXialab** [comment]
Thanks for your reply, could you please tell me is the second columns equal to  the second columns of windows (.bed)? The bed file is generated by hic-pro in the path hic_results/matrix/raw.

**Comment by ay-lab** [comment]
the easiest would be to simply use the --bias option of hicpro2fithic to convert your bias file to a format like the one I sent:
https://github.com/ay-lab/fithic/blob/master/fithic/utils/HiCPro2FitHiC.py

**Comment by LinXialab** [comment]
Thanks for your reply, the head of new biases file is :
chr1    20000   -1

chr1    60000   0.42025596368556184

chr1    100000  0.4929379558831149

chr1    140000  0.2949409959616176

chr1    180000  0.08853618402930381

and the tail is:
chrY    57100000        -1

chrY    57140000        -1

chrY    57180000        -1

chrY    57220000        -1

chrM    20000   0.9640488627509448

But I still got the same error informations.

**Comment by LinXialab** [comment]
The log file is showed as follow:
more TU-2.fithic.log


Interactions file read successfully
--------------------------------------------------------------------------------
----
Observed, Intra-chr in range: pairs= 7710426     totalCount= 7837239
Observed, Intra-chr all: pairs= 7781482  totalCount= 9974057
Observed, Inter-chr all: pairs= 8654050  totalCount= 3143181
Range of observed genomic distances [40000 248120000]

Making equal occupancy bins
--------------------------------------------------------------------------------
----
Observed intra-chr read counts in range 7837239
Desired number of contacts per bin      78372.39,
Number of bins  100
Equal occupancy bins generated

Looping through all possible fragment pairs in-range
--------------------------------------------------------------------------------
----
Chromosome 'chr1',      5657 mappable fragments,        15837535 possible intra-
chr fragment pairs in range,    372372025 possible inter-chr fragment pairs
Chromosome 'chr10',     3283 mappable fragments,        5385692 possible intra-c
hr fragment pairs in range,     223897317 possible inter-chr fragment pairs
Chromosome 'chr11',     3333 mappable fragments,        5551832 possible intra-c
hr fragment pairs in range,     227140617 possible inter-chr fragment pairs
Chromosome 'chr12',     3269 mappable fragments,        5339593 possible intra-c
hr fragment pairs in range,     222988297 possible inter-chr fragment pairs
Chromosome 'chr13',     2399 mappable fragments,        2770831 possible intra-c
hr fragment pairs in range,     165730117 possible inter-chr fragment pairs
Chromosome 'chr14',     2209 mappable fragments,        2331783 possible intra-c
hr fragment pairs in range,     153024057 possible inter-chr fragment pairs
Chromosome 'chr15',     2046 mappable fragments,        1965279 possible intra-c
hr fragment pairs in range,     142066056 possible inter-chr fragment pairs
Chromosome 'chr16',     1973 mappable fragments,        1905475 possible intra-c
hr fragment pairs in range,     137141257 possible inter-chr fragment pairs
Chromosome 'chr17',     1981 mappable fragments,        1956240 possible intra-c
hr fragment pairs in range,     137681481 possible inter-chr fragment pairs
Chromosome 'chr18',     1876 mappable fragments,        1750235 possible intra-c
hr fragment pairs in range,     130580856 possible inter-chr fragment pairs
Chromosome 'chr19',     1392 mappable fragments,        965508 possible intra-ch
r fragment pairs in range,      97565280 possible inter-chr fragment pairs
Chromosome 'chr2',      5953 mappable fragments,        17711078 possible intra-
chr fragment pairs in range,    390094137 possible inter-chr fragment pairs
Chromosome 'chr20',     1546 mappable fragments,        1192332 possible intra-c
hr fragment pairs in range,     108121056 possible inter-chr fragment pairs
Chromosome 'chr21',     912 mappable fragments,         382776 possible intra-ch
r fragment pairs in range,      64359840 possible inter-chr fragment pairs
Chromosome 'chr22',     927 mappable fragments,         370548 possible intra-ch
r fragment pairs in range,      65404485 possible inter-chr fragment pairs
Chromosome 'chr3',      4889 mappable fragments,        11946571 possible intra-
chr fragment pairs in range,    325573177 possible inter-chr fragment pairs
Chromosome 'chr4',      4690 mappable fragments,        10993752 possible intra-
chr fragment pairs in range,    313254480 possible inter-chr fragment pairs
Chromosome 'chr5',      4419 mappable fragments,        9754668 possible intra-c
hr fragment pairs in range,     296351397 possible inter-chr fragment pairs
Chromosome 'chr6',      4220 mappable fragments,        8900962 possible intra-c
hr fragment pairs in range,     283845640 possible inter-chr fragment pairs
Chromosome 'chr7',      3885 mappable fragments,        7539819 possible intra-c
hr fragment pairs in range,     262614345 possible inter-chr fragment pairs
Chromosome 'chr8',      3582 mappable fragments,        6412581 possible intra-c
hr fragment pairs in range,     243217800 possible inter-chr fragment pairs
Chromosome 'chr9',      2927 mappable fragments,        4142545 possible intra-c
hr fragment pairs in range,     200660485 possible inter-chr fragment pairs
Chromosome 'chrM',      1 mappable fragments,   0 possible intra-chr fragment pa
irs in range,   71481 possible inter-chr fragment pairs
Chromosome 'chrX',      3680 mappable fragments,        6746782 possible intra-c
hr fragment pairs in range,     249511360 possible inter-chr fragment pairs
Chromosome 'chrY',      433 mappable fragments,         -396027 possible intra-c
hr fragment pairs in range,     30764217 possible inter-chr fragment pairs
Number of all fragments= 71482
Possible, Intra-chr in range: pairs= 131458390
Possible, Intra-chr all: pairs= 132858273.0
Possible, Inter-chr all: pairs= 2422015630.0
Desired genomic distance range   [0 inf]
Range of possible genomic distances  [40000  248920000]
Baseline intrachromosomal probability is 7.526817693919595e-09
Interchromosomal probability is 4.1287925132010813e-10

**Comment by ay-lab** [comment]
try removing chrY and chrM from all three input files.

**Comment by LinXialab** [comment]
Thanks for your reply. I remove all null lines, chrY, and chrM, it worked!
