### ISSUE TITLE
fithic  run error

### ISSUE THREAD

**Issue by liufuyan2016** [ay-lab/fithic#5]
****Dear professor,**
****I download the fithic, and use the command to setup:**
**python setup.py install --user****

**after setup I run the command:sh run_test.sh
but an error occured below:****

observedIntraInRangeSum	2210827	desiredPerBin	22108	noOfBins	100
Plotting Duan_yeast_EcoRI.fithic_pass1.png
/share/nas2/genome/biosoft/Python/2.7.8/lib/python2.7/site-packages/matplotlib-1.4.3-py2.7-linux-x86_64.egg/matplotlib/collections.py:590: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if self._edgecolors == str('face'):
Writing Duan_yeast_EcoRI.fithic_pass1.txt
Fit a univariate spline to the probability means
baseline intra-chr probability: 1.4239355014175277e-06	baseline inter-chr probability: 1.1954383983420704e-07
Traceback (most recent call last):
  File "/home/liufuyan/.local/bin/fithic", line 9, in <module>
    load_entry_point('fithic==1.0.8', 'console_scripts', 'fithic')()
  File "/home/liufuyan/.local/lib/python2.7/site-packages/fithic-1.0.8-py2.7.egg/fithic/fithic.py", line 184, in main
    splineXinit,splineYinit,splineResidual,isOutlier,splineFDRxinit,splineFDRyinit=fit_Spline(x,y,yerr,options.intersfile,sortedInteractions,biasDic,libname+".spline_pass1",1)
  File "/home/liufuyan/.local/lib/python2.7/site-packages/fithic-1.0.8-py2.7.egg/fithic/fithic.py", line 276, in fit_Spline
    newSplineY = ir.fit_transform(splineX, splineY, increasing=False)
  File "/home/liufuyan/.local/lib/python2.7/site-packages/sklearn/base.py", line 436, in fit_transform
    return self.fit(X, y, **fit_params).transform(X)
TypeError: fit() got an unexpected keyword argument 'increasing'

**Also I meet another issues:**

cannot connect to X server localhost

**Could you provide information how to avoid use the X serve.**

Thank you !

fuyan

**Comment by ay-lab** [comment]
Thanks Fuyan!
Certain versions of scipy had different parameters for the isotonic regression and were treating it differently. Feel free to pull/update your fithic and you should be good to go! With regards to X serve, I'm not sure that is a fithic issue? It is likely an issue dealing with your ssh. 
Thanks!
Arya
