### ISSUE TITLE
fragmentMid 

### ISSUE THREAD

**Issue by BioEpi** [ay-lab/fithic#59]
Hello,
would you like to tell me what fragmentMid reperesent?
how to get the coordinates of 2 loop anchors?

<img width="861" alt="image" src="https://user-images.githubusercontent.com/12387462/182914561-ac5e7b5a-87f0-45a0-9e32-4adf7b7e9a25.png">

**Comment by ay-lab** [comment]
the mid point of the fragment. if your resolution is r, the full coordinates will be: mid - r/2, mid + r/2
