### ISSUE TITLE
--visual flag has cutoff images

### ISSUE THREAD

**Issue by aakashsur** [ay-lab/fithic#8]
Hi, I noticed that while I was using the --visual flag to produce plots, all the plots were slightly cutoff. I imagine this is a matplotlib issue while saving the images, maybe adding plt.tight_layout() or something before saving the image? (Unless it's being drawn with R?)

**Comment by a1kaul** [comment]
Hi! All plots are produced using matplotlib, and for some reason I don't see the same behavior with the -v option. Would you mind including an image of what type of cutoff is being shown?

**Comment by aakashsur** [comment]
Sure, forgot to add them. I've removed the large font size options and scaled up the figure sizes, and that seems to fix most of the single plot ones.

![image](https://user-images.githubusercontent.com/7614271/35844145-d8630186-0ac0-11e8-8aa7-276628e5be47.png)

![image](https://user-images.githubusercontent.com/7614271/35844156-e260c696-0ac0-11e8-8f68-9d4cd035f90b.png)

**Comment by a1kaul** [comment]
Huh that's odd. I think this is something that will need further investigation since you're the only user I know who has experienced that. Does it cause the same issue when you run -v on the test datasets in /fithic/tests/?

**Comment by aakashsur** [comment]
This is the results I original got from the yeast dataset provided in the tests folder:

![yeast fithic_pass6](https://user-images.githubusercontent.com/7614271/35886676-b7104076-0b46-11e8-9ff6-9aa6a8996555.png)

If I remove the matplotlib font sizing options, and increase the figure sizes, they turn out pretty normal:

![image](https://user-images.githubusercontent.com/7614271/35886711-d26b4e92-0b46-11e8-8542-f66c0daa0e05.png)

It's possible it could be an issue with being on the very latest version of matplotlib (2.1.1) Not sure.

**Comment by ay-lab** [comment]
This is odd, but I believe you're correct that it's matplotlib's version. 

I'll keep playing around with the internal code and try to include something that works for all versions in the next release (v.1.1.3). But thank you again for the heads up!
