### ISSUE TITLE
TypeError: coercing to Unicode: need string or buffer, NoneType found

### ISSUE THREAD

**Issue by tiramisutes** [ay-lab/fithic#9]
Hello,
I install the fithic via pip and get follows error when running fithic in the command line:
```
Generating all possible intra-chromosomal fragment pairs and counting the number of all possible inter-chr fragment pairs
------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/public/home/zpxu/miniconda2/bin/fithic", line 11, in <module>
    load_entry_point('fithic==1.1.3', 'console_scripts', 'fithic')()
  File "/public/home/zpxu/miniconda2/lib/python2.7/site-packages/fithic/fithic.py", line 181, in main
    generate_FragPairs(options.fragsfile)
  File "/public/home/zpxu/miniconda2/lib/python2.7/site-packages/fithic/fithic.py", line 756, in generate_FragPairs
    infile = open(infilename, 'r')
TypeError: coercing to Unicode: need string or buffer, NoneType found
```

Any help is much appreciated.
Thanks.

**Comment by aryakaul** [comment]
Hi! Based on the error it seems like you aren't using the '-f' flag. This option is required, and you would need to use it for the proper functioning of FitHiC (see README for more details).

If you are using the flag, but still seeing the error; could you post the command you're using here?

Best,
Arya

**Comment by tiramisutes** [comment]
Hello,
Yes, I used the `-f` parameter and run as follows command: 
```
fithic-runner.py -f L2_1_2.hicup.bam.equal_binning.txt -i L2_1_2.hicup.bam.interactions.txt -p 3 -b 200 -o Fit-Hi-C -l "hujiao"
```
And get the error stdout:
```
Total of        1 observed intra-chr fragment pairs,    0 observed intra-chr fragment pairs in range,   36 observed inter-chr fragment pairs
Total of        1 observed intra-chr read counts,       0 observed intra-chr read counts in range,      46 observed inter-chr read counts
Range of observed genomic distances   [0 0]
Total time for sorting interactions according to genomic distance: 0.000

Calculating probability means and standard deviations by equal occupancy binning of interaction data
------------------------------------------------------------------------------------
observedIntraInRangeSum 0       desiredPerBin   0       noOfBins        200
Writing hujiao.fithic_pass1.txt

Fit a univariate spline to the probability means
------------------------------------------------------------------------------------
baseline intra-chr probability: 0.0015923566878980893   baseline inter-chr probability: 5.495857885016818e-11
Traceback (most recent call last):
  File "fithic-runner.py", line 6, in <module>
    main()
  File "/public/home/software/fithic/fithic/fithic.py", line 191, in main
    splineXinit,splineYinit,splineResidual,isOutlier,splineFDRxinit,splineFDRyinit=fit_Spline(x,y,yerr,options.intersfile,sortedInteractions,biasDic,libname+".spline_pass1",1)
  File "/public/home/software/fithic/fithic/fithic.py", line 260, in fit_Spline
    xi = np.linspace(min(x), max(x), overSample*len(x))
ValueError: min() arg is an empty sequence
```

Any help is much appreciated.
Thanks.

**Comment by aryakaul** [comment]
Hi,

So just to clarify, the error you are showing now is distinct from your first reported error. This second error is symptomatic of whatever your input file is. This line:

`Total of  1 observed intra-chr fragment pairs,    0 observed intra-chr fragment pairs in range,   36 observed inter-chr fragment pairs`

Indicates that your input file has no intra-chromosomal contact counts in range, and you would see the result shown. If your goal is to analyze inter-chromosomal interactions then the -x flag should be used (look at README for more info). 

As it stands, I am unsure what type of input files you are using, as nearly all should have significantly more interactions than what you are seeing.

**Comment by iceduangbing** [comment]
hello
  I don't know what the -p means ,through i have read the paper.

**Comment by iceduangbing** [comment]
hello 
 I don't know what the -p means,though I had read the paper.my statistics knowledge is poor.
   Any help is much appreciated.
   thanks

**Comment by iceduangbing** [comment]
hello
I don't know what the -p means,though I had read the paper.my statistics knowledge is poor.
moreover, dose the input file need to ICE?
Any help is much appreciated.
thanks

**Comment by lucaspatel** [comment]
The paper's methods describe how Fit-Hi-C uses a spline fitting procedure when generating a genomic distance versus contract probability model. In doing this, we can more accurately estimate contact probability since we're not constrained by fixed-width binning. In the process of spline fitting performed by Fit-Hi-C, the spline is fit several times, with each iteration removing the most significant outliers in order to converge the spline on the most representative points. This process can be repeated multiple times to further converge the spline, but after a certain number of passes, changes in the spline will be seemingly indistinguishable. You can use the '-p' flag to induce more passes of the spline-fitting beyond what Fit-Hi-C will do naturally, but you will likely not see a noticeable effect unless your data is particularly dispersed.

You can pass the the bias values generated from doing ICE as input into Fit-Hi-C using the '-t' flag.

**Comment by iceduangbing** [comment]
thanks
 so what you mean  that I need input the contact rawmatrix before ICE and the bias values after ICE ? furthermore the '-b' flag ,my data is divided to 373 bins,so I should set -b 373 ?

**Comment by iceduangbing** [comment]
hello 
  what does the nooflocouspaire of the first outputfile mean ？
 Any help is much appreciated.

**Comment by aryakaul** [comment]
How many interaction pairs we observe at a given genomic distance. For example, within the output file example in the README, at the given distance of 20077, the probability of a contact is 2.38e-05, the number of interaction pairs is 210, and the total sum of all contacts at this distance is 19574.
